name: Expressions Example

on:
  workflow_dispatch:


jobs:
  expressions:
    runs_on: ubuntu-latest
    steps:
      - name: is equals to
        run: echo "5==5->${{ 5==5 }}"

      - name: is not equals to
        run: echo "5!=5->${{ 5!=5 }}"

      - name: is less than
        run: echo "4<=3->${{ 4==3 }}"

      - name: github.ref_name is equals to 'main'
        run: echo "Is ref_name 'main':\ ${{ 'main' == github.ref_name }}"