name: Job Level If Conditions

on:
  workflow_dispatch:

jobs:
  needs_linux:
    runs-on: ubuntu-latest
    if: vars.required_os != 'Windows'
    steps:
      - name: Print Requied OS
        run: echo "Runner OS => ${{ vars.required_os }}"

  only_on_master:
    if: github.ref_name == 'master'
    runs-on: windows-latest
    steps:
      - name: Print Branch Name
        run: echo "Branch Name => ${{ github.ref_name }}"