name: Passing Data Between Steps

on:
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step Stores 'username=alice'
        id: first_step # required to get output in the next step
        run: echo "username=alice"  >> "$GITHUB_OUTPUT"

      - name: Second Step Retrives `username`
        run: echo "username=${{ steps.first_step.output.username }}"
