name: Secrets Leaked

on:
  workflow_dispatch:

jobs:
  leaked:
    runs-on: ubuntu-latest
    steps:
    - name: Leak Secrets
      # env:
      #   PROD_TOKEN: "${{ secrets.PRODUCTION_TOKEN }}"
      run: echo "Base64 Secret='${{ secrets.PRODUCTION_TOKEN }}'" | base64