name: Secrets Leaked
on:
  workflow_dispatch:
#  push:

jobs:
  leak-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Attempt Direct Print (Masked)
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          # This will safely print as "***"
          echo "Direct print: $MY_SECRET"

      - name: Exploit Encoding (Unmasked)
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          # Encoding the secret changes the string structure.
          # GitHub's log filter won't recognize it, printing it clearly.
          echo "Encoded print:"
          echo -n "$MY_SECRET" | base64 | base64 | base64
          echo -n "$MY_SECRET" | sed 's/./& /g'
          echo ${{ secrets.MY_SECRET }} | sed 's/./& /g' # however this won't work
