name: Strategy Matrix

on: [workflow_dispatch]

jobs:
  matrix_demo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nums: [1,2]
        alphabets: [a,b]

    steps:
      - name: Print Num
        run: echo "Num=${{ matrix.nums }}, Alphabet=${{ matrix.alphabets }}"