name: Test Matrix failures

on:
  workflow_dispatch:

jobs:
  some-job:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.python-version != '3.13' }}
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Python python-version (`import cgi` Breaks in 3.13+)
        run: python -c "import sys; import cgi; print(sys.version)"

