name: Continue on Error Check + Max Parallel

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.nums !=5 }}

    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        nums: [1, 5, 9]

    steps:
      - name: Print Num ${{ matrix.nums }}
        run: |
          if [[ "${{ matrix.nums }}" -eq 5 ]]; then
            exit 1
          fi
          echo "Num=${{ matrix.nums }}"
